name: 'DELETE /api/files/:dir[/:file]'

inputs:
  api_url:
    type: string
    required: true
  basic_auth_user:
    type: string
    required: false
  basic_auth_pass:
    type: string
    required: false
  dir:
    type: string
    required: true
  file:
    type: string

outputs:
  response:
    value: ${{ steps.curl.outputs.response }}

runs:
  using: composite
  steps:
    - id: curl
      env:
        GITHUB_INPUTS: ${{ toJSON(inputs) }}
      shell: perl {0}
      run: |
        use File::Basename;
        use lib sprintf('%s/../../../lib', dirname($ENV{GITHUB_ACTION_PATH}));
        use GithubAptlyAction;
        GithubAptlyAction::Files::delete;
