name: 'POST /api/repos'

inputs:
  api_url:
    type: string
    required: true
  basic_auth_user:
    type: string
    required: false
  basic_auth_pass:
    type: string
    required: false
  allow_failure:
    type: boolean
    default: false
  name:
    type: string
    required: true
  comment:
    type: string
  default_distribution:
    type: string
  default_component:
    type: string

outputs:
  response:
    value: ${{ steps.curl.outputs.response }}

runs:
  using: composite
  steps:
    - id: curl
      shell: perl {0}
      env:
        GITHUB_INPUTS: ${{ toJSON(inputs) }}
      run: |
        use File::Basename;
        use lib sprintf('%s/../../../lib', dirname($ENV{GITHUB_ACTION_PATH}));
        use GithubAptlyAction;
        GithubAptlyAction::Repos::create;
