name: 'PUT /api/publish/:prefix/:distribution'

inputs:
  api_url:
    type: string
    required: true
  basic_auth_user:
    type: string
    required: false
  basic_auth_pass:
    type: string
    required: false
  allow_failure:
    type: boolean
    default: false
  prefix:
    type: string
    required: true
  distribution:
    type: string
    required: true
  Snapshots:
    type: string
    required: false
    comment: >
      only when updating published snapshots, list of objects Component/Name
  ForceOverwrite:
    type: boolean
  SigningSkip:
    type: boolean
  SigningBatch:
    type: boolean
  SigningGpgKey:
    type: string
  SigningKeyring:
    type: string
  SigningSecretKeyring:
    type: string
  SigningPassphrase:
    type: string
  SigningPassphraseFile:
    type: string
  AcquireByHash:
    type: boolean

outputs:
  response:
    value: ${{ steps.curl.outputs.response }}

runs:
  using: composite
  steps:
    - id: curl
      env:
        GITHUB_INPUTS: ${{ toJSON(inputs) }}
      shell: perl {0}
      run: |
        use File::Basename;
        use lib sprintf('%s/../../../lib', dirname($ENV{GITHUB_ACTION_PATH}));
        use GithubAptlyAction;
        GithubAptlyAction::Publication::update;
