name: ci
on:
  workflow_dispatch:
  push:

jobs:
  repos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./actions/aptly/repos/list
        id: step1
        with:
          api_url: ${{ secrets.APTLY_API_URL }}
          basic_auth_user: ${{ secrets.APTLY_BASIC_AUTH_USER }}
          basic_auth_pass: ${{ secrets.APTLY_BASIC_AUTH_PASS }}
      - run: echo '${{ steps.step1.outputs.response }}' | jq .

      - uses: ./actions/aptly/repos/create
        id: step2
        with:
          api_url: ${{ secrets.APTLY_API_URL }}
          basic_auth_user: ${{ secrets.APTLY_BASIC_AUTH_USER }}
          basic_auth_pass: ${{ secrets.APTLY_BASIC_AUTH_PASS }}
          name: ${{ github.repository }}-${{ github.run_id }}
          comment: myComment
          default_distribution: myDistribution
          default_component: myComponent
      - run: echo '${{ steps.step2.outputs.response }}' | jq .

      - uses: ./actions/aptly/repos/list
        id: step3
        with:
          api_url: ${{ secrets.APTLY_API_URL }}
          basic_auth_user: ${{ secrets.APTLY_BASIC_AUTH_USER }}
          basic_auth_pass: ${{ secrets.APTLY_BASIC_AUTH_PASS }}
      - run: echo '${{ steps.step3.outputs.response }}' | jq .

      - uses: ./actions/aptly/repos/delete
        id: step4
        with:
          api_url: ${{ secrets.APTLY_API_URL }}
          basic_auth_user: ${{ secrets.APTLY_BASIC_AUTH_USER }}
          basic_auth_pass: ${{ secrets.APTLY_BASIC_AUTH_PASS }}
          name: ${{ github.repository }}-${{ github.run_id }}
      - run: echo '${{ steps.step4.outputs.response }}' | jq .

      - uses: ./actions/aptly/repos/list
        id: step5
        with:
          api_url: ${{ secrets.APTLY_API_URL }}
          basic_auth_user: ${{ secrets.APTLY_BASIC_AUTH_USER }}
          basic_auth_pass: ${{ secrets.APTLY_BASIC_AUTH_PASS }}
      - run: echo '${{ steps.step5.outputs.response }}' | jq .

  files:
    runs-on: ubuntu-latest
    needs:
      - repos
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/aptly/files/list
        id: step1
        with:
          api_url: ${{ secrets.APTLY_API_URL }}
          basic_auth_user: ${{ secrets.APTLY_BASIC_AUTH_USER }}
          basic_auth_pass: ${{ secrets.APTLY_BASIC_AUTH_PASS }}
      - run: echo '${{ steps.step1.outputs.response }}' | jq .

      - uses: ./actions/aptly/files/upload
        id: step2
        with:
          api_url: ${{ secrets.APTLY_API_URL }}
          basic_auth_user: ${{ secrets.APTLY_BASIC_AUTH_USER }}
          basic_auth_pass: ${{ secrets.APTLY_BASIC_AUTH_PASS }}
          dir: ${{ github.repository }}-${{ github.run_id }}
          files: |
            /usr/lib/os-release
            /etc/passwd
      - run: echo '${{ steps.step2.outputs.response }}' | jq .

      - uses: ./actions/aptly/files/list
        id: step3
        with:
          api_url: ${{ secrets.APTLY_API_URL }}
          basic_auth_user: ${{ secrets.APTLY_BASIC_AUTH_USER }}
          basic_auth_pass: ${{ secrets.APTLY_BASIC_AUTH_PASS }}
      - run: echo '${{ steps.step3.outputs.response }}' | jq .

      - uses: ./actions/aptly/files/list
        id: step4
        with:
          api_url: ${{ secrets.APTLY_API_URL }}
          basic_auth_user: ${{ secrets.APTLY_BASIC_AUTH_USER }}
          basic_auth_pass: ${{ secrets.APTLY_BASIC_AUTH_PASS }}
          dir: ${{ github.repository }}-${{ github.run_id }}
      - run: echo '${{ steps.step4.outputs.response }}' | jq .

      - uses: ./actions/aptly/files/delete
        id: step5
        with:
          api_url: ${{ secrets.APTLY_API_URL }}
          basic_auth_user: ${{ secrets.APTLY_BASIC_AUTH_USER }}
          basic_auth_pass: ${{ secrets.APTLY_BASIC_AUTH_PASS }}
          dir: ${{ github.repository }}-${{ github.run_id }}
      - run: echo '${{ steps.step5.outputs.response }}' | jq .

      - uses: ./actions/aptly/files/list
        id: step6
        with:
          api_url: ${{ secrets.APTLY_API_URL }}
          basic_auth_user: ${{ secrets.APTLY_BASIC_AUTH_USER }}
          basic_auth_pass: ${{ secrets.APTLY_BASIC_AUTH_PASS }}
      - run: echo '${{ steps.step6.outputs.response }}' | jq .

  add:
    runs-on: ubuntu-latest
    needs:
      - files
    steps:
      - uses: actions/checkout@v3

      - uses: ./actions/aptly/repos/create
        id: step1
        with:
          api_url: ${{ secrets.APTLY_API_URL }}
          basic_auth_user: ${{ secrets.APTLY_BASIC_AUTH_USER }}
          basic_auth_pass: ${{ secrets.APTLY_BASIC_AUTH_PASS }}
          name: ${{ github.repository }}-${{ github.run_id }}
      - run: echo '${{ steps.step1.outputs.response }}' | jq .

      - uses: ./actions/aptly/files/upload
        id: step2
        with:
          api_url: ${{ secrets.APTLY_API_URL }}
          basic_auth_user: ${{ secrets.APTLY_BASIC_AUTH_USER }}
          basic_auth_pass: ${{ secrets.APTLY_BASIC_AUTH_PASS }}
          dir: ${{ github.repository }}-${{ github.run_id }}
          files: |
            /usr/lib/os-release
            /etc/passwd
            /var/cache/apt/archives/*.deb
      - run: echo '${{ steps.step2.outputs.response }}' | jq .

      - uses: ./actions/aptly/repos/add
        id: step3
        with:
          api_url: ${{ secrets.APTLY_API_URL }}
          basic_auth_user: ${{ secrets.APTLY_BASIC_AUTH_USER }}
          basic_auth_pass: ${{ secrets.APTLY_BASIC_AUTH_PASS }}
          name: ${{ github.repository }}-${{ github.run_id }}
          dir: ${{ github.repository }}-${{ github.run_id }}
      - run: echo '${{ steps.step3.outputs.response }}' | jq .

      - uses: ./actions/aptly/repos/search
        id: step4
        with:
          api_url: ${{ secrets.APTLY_API_URL }}
          basic_auth_user: ${{ secrets.APTLY_BASIC_AUTH_USER }}
          basic_auth_pass: ${{ secrets.APTLY_BASIC_AUTH_PASS }}
          name: ${{ github.repository }}-${{ github.run_id }}
          format: details
      - run: echo '${{ steps.step4.outputs.response }}' | jq .

      - uses: ./actions/aptly/publication/publish
        id: step5
        with:
          api_url: ${{ secrets.APTLY_API_URL }}
          basic_auth_user: ${{ secrets.APTLY_BASIC_AUTH_USER }}
          basic_auth_pass: ${{ secrets.APTLY_BASIC_AUTH_PASS }}
          prefix: ${{ github.repository }}-${{ github.run_id }}
          Distribution: unstable
          SourceKind: local
          Sources: '[{"Name": "${{ github.repository }}"}]'
          Architectures: '["amd64"]'
          SigningSkip: true
      - run: echo '${{ steps.step5.outputs.response }}' | jq .
